[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["Hayato Sasaki <h.sasaki.ynu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
