version: '3'

includes:
  lint:
    dir: .
    taskfile: tasks/taskfile.lint.yaml
  init:
    taskfile: tasks/taskfile.init.yaml
tasks:
  run:
    desc: 'run server'
    cmd: poetry run uvicorn demo.main:app --reload
  test:
    desc: 'run tests'
    deps:
      - lint:check
    cmd: poetry run pytest tests