version: '3'

includes:
  lint:
    dir: .
    taskfile: tasks/taskfile.lint.yaml
tasks:
  init:
    desc: 'initiate this project'
    cmd: poetry install
  run:
    desc: 'run server'
    cmd: poetry run uvicorn demo.main:app --reload