version: '3'

tasks:
  check:
    desc: 'check lint and format error'
    cmds:
      - poetry run ruff format --check
      - poetry run ruff check
  fix:
    desc: 'check lint error'
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix
