version: '3'

tasks:
  check:
    desc: 'check lint, format, type error'
    cmds:
      - poetry run ruff format --check
      - poetry run ruff check
      - poetry run mypy demo tests
  fix:
    desc: 'check lint error'
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix
